/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Layer2TransactionWhereInput } from "./Layer2TransactionWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Layer2TransactionListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Layer2TransactionWhereInput,
  })
  @ValidateNested()
  @Type(() => Layer2TransactionWhereInput)
  @IsOptional()
  @Field(() => Layer2TransactionWhereInput, {
    nullable: true,
  })
  every?: Layer2TransactionWhereInput;

  @ApiProperty({
    required: false,
    type: () => Layer2TransactionWhereInput,
  })
  @ValidateNested()
  @Type(() => Layer2TransactionWhereInput)
  @IsOptional()
  @Field(() => Layer2TransactionWhereInput, {
    nullable: true,
  })
  some?: Layer2TransactionWhereInput;

  @ApiProperty({
    required: false,
    type: () => Layer2TransactionWhereInput,
  })
  @ValidateNested()
  @Type(() => Layer2TransactionWhereInput)
  @IsOptional()
  @Field(() => Layer2TransactionWhereInput, {
    nullable: true,
  })
  none?: Layer2TransactionWhereInput;
}
export { Layer2TransactionListRelationFilter as Layer2TransactionListRelationFilter };
