/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Layer2TransactionWhereInput } from "./Layer2TransactionWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Layer2TransactionOrderByInput } from "./Layer2TransactionOrderByInput";

@ArgsType()
class Layer2TransactionFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Layer2TransactionWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Layer2TransactionWhereInput, { nullable: true })
  @Type(() => Layer2TransactionWhereInput)
  where?: Layer2TransactionWhereInput;

  @ApiProperty({
    required: false,
    type: [Layer2TransactionOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Layer2TransactionOrderByInput], { nullable: true })
  @Type(() => Layer2TransactionOrderByInput)
  orderBy?: Array<Layer2TransactionOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Layer2TransactionFindManyArgs as Layer2TransactionFindManyArgs };
