/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Validator } from "./Validator";
import { ValidatorCountArgs } from "./ValidatorCountArgs";
import { ValidatorFindManyArgs } from "./ValidatorFindManyArgs";
import { ValidatorFindUniqueArgs } from "./ValidatorFindUniqueArgs";
import { DeleteValidatorArgs } from "./DeleteValidatorArgs";
import { ValidatorService } from "../validator.service";
@graphql.Resolver(() => Validator)
export class ValidatorResolverBase {
  constructor(protected readonly service: ValidatorService) {}

  async _validatorsMeta(
    @graphql.Args() args: ValidatorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Validator])
  async validators(
    @graphql.Args() args: ValidatorFindManyArgs
  ): Promise<Validator[]> {
    return this.service.validators(args);
  }

  @graphql.Query(() => Validator, { nullable: true })
  async validator(
    @graphql.Args() args: ValidatorFindUniqueArgs
  ): Promise<Validator | null> {
    const result = await this.service.validator(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Validator)
  async deleteValidator(
    @graphql.Args() args: DeleteValidatorArgs
  ): Promise<Validator | null> {
    try {
      return await this.service.deleteValidator(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
