/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ValidatorSlash } from "./ValidatorSlash";
import { ValidatorSlashCountArgs } from "./ValidatorSlashCountArgs";
import { ValidatorSlashFindManyArgs } from "./ValidatorSlashFindManyArgs";
import { ValidatorSlashFindUniqueArgs } from "./ValidatorSlashFindUniqueArgs";
import { DeleteValidatorSlashArgs } from "./DeleteValidatorSlashArgs";
import { ValidatorSlashService } from "../validatorSlash.service";
@graphql.Resolver(() => ValidatorSlash)
export class ValidatorSlashResolverBase {
  constructor(protected readonly service: ValidatorSlashService) {}

  async _validatorSlashesMeta(
    @graphql.Args() args: ValidatorSlashCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ValidatorSlash])
  async validatorSlashes(
    @graphql.Args() args: ValidatorSlashFindManyArgs
  ): Promise<ValidatorSlash[]> {
    return this.service.validatorSlashes(args);
  }

  @graphql.Query(() => ValidatorSlash, { nullable: true })
  async validatorSlash(
    @graphql.Args() args: ValidatorSlashFindUniqueArgs
  ): Promise<ValidatorSlash | null> {
    const result = await this.service.validatorSlash(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ValidatorSlash)
  async deleteValidatorSlash(
    @graphql.Args() args: DeleteValidatorSlashArgs
  ): Promise<ValidatorSlash | null> {
    try {
      return await this.service.deleteValidatorSlash(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
