/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrphanedBlock } from "./OrphanedBlock";
import { OrphanedBlockCountArgs } from "./OrphanedBlockCountArgs";
import { OrphanedBlockFindManyArgs } from "./OrphanedBlockFindManyArgs";
import { OrphanedBlockFindUniqueArgs } from "./OrphanedBlockFindUniqueArgs";
import { DeleteOrphanedBlockArgs } from "./DeleteOrphanedBlockArgs";
import { OrphanedBlockService } from "../orphanedBlock.service";
@graphql.Resolver(() => OrphanedBlock)
export class OrphanedBlockResolverBase {
  constructor(protected readonly service: OrphanedBlockService) {}

  async _orphanedBlocksMeta(
    @graphql.Args() args: OrphanedBlockCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrphanedBlock])
  async orphanedBlocks(
    @graphql.Args() args: OrphanedBlockFindManyArgs
  ): Promise<OrphanedBlock[]> {
    return this.service.orphanedBlocks(args);
  }

  @graphql.Query(() => OrphanedBlock, { nullable: true })
  async orphanedBlock(
    @graphql.Args() args: OrphanedBlockFindUniqueArgs
  ): Promise<OrphanedBlock | null> {
    const result = await this.service.orphanedBlock(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrphanedBlock)
  async deleteOrphanedBlock(
    @graphql.Args() args: DeleteOrphanedBlockArgs
  ): Promise<OrphanedBlock | null> {
    try {
      return await this.service.deleteOrphanedBlock(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
