/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Rollup as PrismaRollup } from "@prisma/client";

export class RollupServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RollupCountArgs, "select">): Promise<number> {
    return this.prisma.rollup.count(args);
  }

  async rollups(args: Prisma.RollupFindManyArgs): Promise<PrismaRollup[]> {
    return this.prisma.rollup.findMany(args);
  }
  async rollup(
    args: Prisma.RollupFindUniqueArgs
  ): Promise<PrismaRollup | null> {
    return this.prisma.rollup.findUnique(args);
  }
  async createRollup(args: Prisma.RollupCreateArgs): Promise<PrismaRollup> {
    return this.prisma.rollup.create(args);
  }
  async updateRollup(args: Prisma.RollupUpdateArgs): Promise<PrismaRollup> {
    return this.prisma.rollup.update(args);
  }
  async deleteRollup(args: Prisma.RollupDeleteArgs): Promise<PrismaRollup> {
    return this.prisma.rollup.delete(args);
  }
}
