/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CrossChainTransaction } from "./CrossChainTransaction";
import { CrossChainTransactionCountArgs } from "./CrossChainTransactionCountArgs";
import { CrossChainTransactionFindManyArgs } from "./CrossChainTransactionFindManyArgs";
import { CrossChainTransactionFindUniqueArgs } from "./CrossChainTransactionFindUniqueArgs";
import { DeleteCrossChainTransactionArgs } from "./DeleteCrossChainTransactionArgs";
import { CrossChainTransactionService } from "../crossChainTransaction.service";
@graphql.Resolver(() => CrossChainTransaction)
export class CrossChainTransactionResolverBase {
  constructor(protected readonly service: CrossChainTransactionService) {}

  async _crossChainTransactionsMeta(
    @graphql.Args() args: CrossChainTransactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CrossChainTransaction])
  async crossChainTransactions(
    @graphql.Args() args: CrossChainTransactionFindManyArgs
  ): Promise<CrossChainTransaction[]> {
    return this.service.crossChainTransactions(args);
  }

  @graphql.Query(() => CrossChainTransaction, { nullable: true })
  async crossChainTransaction(
    @graphql.Args() args: CrossChainTransactionFindUniqueArgs
  ): Promise<CrossChainTransaction | null> {
    const result = await this.service.crossChainTransaction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CrossChainTransaction)
  async deleteCrossChainTransaction(
    @graphql.Args() args: DeleteCrossChainTransactionArgs
  ): Promise<CrossChainTransaction | null> {
    try {
      return await this.service.deleteCrossChainTransaction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
