/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Crowdfunding } from "./Crowdfunding";
import { CrowdfundingCountArgs } from "./CrowdfundingCountArgs";
import { CrowdfundingFindManyArgs } from "./CrowdfundingFindManyArgs";
import { CrowdfundingFindUniqueArgs } from "./CrowdfundingFindUniqueArgs";
import { DeleteCrowdfundingArgs } from "./DeleteCrowdfundingArgs";
import { CrowdfundingService } from "../crowdfunding.service";
@graphql.Resolver(() => Crowdfunding)
export class CrowdfundingResolverBase {
  constructor(protected readonly service: CrowdfundingService) {}

  async _crowdfundingsMeta(
    @graphql.Args() args: CrowdfundingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Crowdfunding])
  async crowdfundings(
    @graphql.Args() args: CrowdfundingFindManyArgs
  ): Promise<Crowdfunding[]> {
    return this.service.crowdfundings(args);
  }

  @graphql.Query(() => Crowdfunding, { nullable: true })
  async crowdfunding(
    @graphql.Args() args: CrowdfundingFindUniqueArgs
  ): Promise<Crowdfunding | null> {
    const result = await this.service.crowdfunding(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Crowdfunding)
  async deleteCrowdfunding(
    @graphql.Args() args: DeleteCrowdfundingArgs
  ): Promise<Crowdfunding | null> {
    try {
      return await this.service.deleteCrowdfunding(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
