/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PriceFeed } from "./PriceFeed";
import { PriceFeedCountArgs } from "./PriceFeedCountArgs";
import { PriceFeedFindManyArgs } from "./PriceFeedFindManyArgs";
import { PriceFeedFindUniqueArgs } from "./PriceFeedFindUniqueArgs";
import { DeletePriceFeedArgs } from "./DeletePriceFeedArgs";
import { PriceFeedService } from "../priceFeed.service";
@graphql.Resolver(() => PriceFeed)
export class PriceFeedResolverBase {
  constructor(protected readonly service: PriceFeedService) {}

  async _priceFeedsMeta(
    @graphql.Args() args: PriceFeedCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PriceFeed])
  async priceFeeds(
    @graphql.Args() args: PriceFeedFindManyArgs
  ): Promise<PriceFeed[]> {
    return this.service.priceFeeds(args);
  }

  @graphql.Query(() => PriceFeed, { nullable: true })
  async priceFeed(
    @graphql.Args() args: PriceFeedFindUniqueArgs
  ): Promise<PriceFeed | null> {
    const result = await this.service.priceFeed(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PriceFeed)
  async deletePriceFeed(
    @graphql.Args() args: DeletePriceFeedArgs
  ): Promise<PriceFeed | null> {
    try {
      return await this.service.deletePriceFeed(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
