/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { BugBounty } from "./BugBounty";
import { BugBountyCountArgs } from "./BugBountyCountArgs";
import { BugBountyFindManyArgs } from "./BugBountyFindManyArgs";
import { BugBountyFindUniqueArgs } from "./BugBountyFindUniqueArgs";
import { DeleteBugBountyArgs } from "./DeleteBugBountyArgs";
import { BugBountyService } from "../bugBounty.service";
@graphql.Resolver(() => BugBounty)
export class BugBountyResolverBase {
  constructor(protected readonly service: BugBountyService) {}

  async _bugBountiesMeta(
    @graphql.Args() args: BugBountyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [BugBounty])
  async bugBounties(
    @graphql.Args() args: BugBountyFindManyArgs
  ): Promise<BugBounty[]> {
    return this.service.bugBounties(args);
  }

  @graphql.Query(() => BugBounty, { nullable: true })
  async bugBounty(
    @graphql.Args() args: BugBountyFindUniqueArgs
  ): Promise<BugBounty | null> {
    const result = await this.service.bugBounty(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BugBounty)
  async deleteBugBounty(
    @graphql.Args() args: DeleteBugBountyArgs
  ): Promise<BugBounty | null> {
    try {
      return await this.service.deleteBugBounty(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
