/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Staking } from "./Staking";
import { StakingCountArgs } from "./StakingCountArgs";
import { StakingFindManyArgs } from "./StakingFindManyArgs";
import { StakingFindUniqueArgs } from "./StakingFindUniqueArgs";
import { DeleteStakingArgs } from "./DeleteStakingArgs";
import { StakingService } from "../staking.service";
@graphql.Resolver(() => Staking)
export class StakingResolverBase {
  constructor(protected readonly service: StakingService) {}

  async _stakingsMeta(
    @graphql.Args() args: StakingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Staking])
  async stakings(
    @graphql.Args() args: StakingFindManyArgs
  ): Promise<Staking[]> {
    return this.service.stakings(args);
  }

  @graphql.Query(() => Staking, { nullable: true })
  async staking(
    @graphql.Args() args: StakingFindUniqueArgs
  ): Promise<Staking | null> {
    const result = await this.service.staking(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Staking)
  async deleteStaking(
    @graphql.Args() args: DeleteStakingArgs
  ): Promise<Staking | null> {
    try {
      return await this.service.deleteStaking(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
