/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TokenBalance } from "./TokenBalance";
import { TokenBalanceCountArgs } from "./TokenBalanceCountArgs";
import { TokenBalanceFindManyArgs } from "./TokenBalanceFindManyArgs";
import { TokenBalanceFindUniqueArgs } from "./TokenBalanceFindUniqueArgs";
import { DeleteTokenBalanceArgs } from "./DeleteTokenBalanceArgs";
import { TokenBalanceService } from "../tokenBalance.service";
@graphql.Resolver(() => TokenBalance)
export class TokenBalanceResolverBase {
  constructor(protected readonly service: TokenBalanceService) {}

  async _tokenBalancesMeta(
    @graphql.Args() args: TokenBalanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TokenBalance])
  async tokenBalances(
    @graphql.Args() args: TokenBalanceFindManyArgs
  ): Promise<TokenBalance[]> {
    return this.service.tokenBalances(args);
  }

  @graphql.Query(() => TokenBalance, { nullable: true })
  async tokenBalance(
    @graphql.Args() args: TokenBalanceFindUniqueArgs
  ): Promise<TokenBalance | null> {
    const result = await this.service.tokenBalance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TokenBalance)
  async deleteTokenBalance(
    @graphql.Args() args: DeleteTokenBalanceArgs
  ): Promise<TokenBalance | null> {
    try {
      return await this.service.deleteTokenBalance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
