/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Network } from "./Network";
import { NetworkCountArgs } from "./NetworkCountArgs";
import { NetworkFindManyArgs } from "./NetworkFindManyArgs";
import { NetworkFindUniqueArgs } from "./NetworkFindUniqueArgs";
import { DeleteNetworkArgs } from "./DeleteNetworkArgs";
import { NetworkService } from "../network.service";
@graphql.Resolver(() => Network)
export class NetworkResolverBase {
  constructor(protected readonly service: NetworkService) {}

  async _networksMeta(
    @graphql.Args() args: NetworkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Network])
  async networks(
    @graphql.Args() args: NetworkFindManyArgs
  ): Promise<Network[]> {
    return this.service.networks(args);
  }

  @graphql.Query(() => Network, { nullable: true })
  async network(
    @graphql.Args() args: NetworkFindUniqueArgs
  ): Promise<Network | null> {
    const result = await this.service.network(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Network)
  async deleteNetwork(
    @graphql.Args() args: DeleteNetworkArgs
  ): Promise<Network | null> {
    try {
      return await this.service.deleteNetwork(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
