/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SyncStatus } from "./SyncStatus";
import { SyncStatusCountArgs } from "./SyncStatusCountArgs";
import { SyncStatusFindManyArgs } from "./SyncStatusFindManyArgs";
import { SyncStatusFindUniqueArgs } from "./SyncStatusFindUniqueArgs";
import { DeleteSyncStatusArgs } from "./DeleteSyncStatusArgs";
import { SyncStatusService } from "../syncStatus.service";
@graphql.Resolver(() => SyncStatus)
export class SyncStatusResolverBase {
  constructor(protected readonly service: SyncStatusService) {}

  async _syncStatusesMeta(
    @graphql.Args() args: SyncStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SyncStatus])
  async syncStatuses(
    @graphql.Args() args: SyncStatusFindManyArgs
  ): Promise<SyncStatus[]> {
    return this.service.syncStatuses(args);
  }

  @graphql.Query(() => SyncStatus, { nullable: true })
  async syncStatus(
    @graphql.Args() args: SyncStatusFindUniqueArgs
  ): Promise<SyncStatus | null> {
    const result = await this.service.syncStatus(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SyncStatus)
  async deleteSyncStatus(
    @graphql.Args() args: DeleteSyncStatusArgs
  ): Promise<SyncStatus | null> {
    try {
      return await this.service.deleteSyncStatus(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
