/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Bridge } from "./Bridge";
import { BridgeCountArgs } from "./BridgeCountArgs";
import { BridgeFindManyArgs } from "./BridgeFindManyArgs";
import { BridgeFindUniqueArgs } from "./BridgeFindUniqueArgs";
import { DeleteBridgeArgs } from "./DeleteBridgeArgs";
import { BridgeService } from "../bridge.service";
@graphql.Resolver(() => Bridge)
export class BridgeResolverBase {
  constructor(protected readonly service: BridgeService) {}

  async _bridgesMeta(
    @graphql.Args() args: BridgeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Bridge])
  async bridges(@graphql.Args() args: BridgeFindManyArgs): Promise<Bridge[]> {
    return this.service.bridges(args);
  }

  @graphql.Query(() => Bridge, { nullable: true })
  async bridge(
    @graphql.Args() args: BridgeFindUniqueArgs
  ): Promise<Bridge | null> {
    const result = await this.service.bridge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Bridge)
  async deleteBridge(
    @graphql.Args() args: DeleteBridgeArgs
  ): Promise<Bridge | null> {
    try {
      return await this.service.deleteBridge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
