/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TransactionAudit } from "./TransactionAudit";
import { TransactionAuditCountArgs } from "./TransactionAuditCountArgs";
import { TransactionAuditFindManyArgs } from "./TransactionAuditFindManyArgs";
import { TransactionAuditFindUniqueArgs } from "./TransactionAuditFindUniqueArgs";
import { DeleteTransactionAuditArgs } from "./DeleteTransactionAuditArgs";
import { TransactionAuditService } from "../transactionAudit.service";
@graphql.Resolver(() => TransactionAudit)
export class TransactionAuditResolverBase {
  constructor(protected readonly service: TransactionAuditService) {}

  async _transactionAuditsMeta(
    @graphql.Args() args: TransactionAuditCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TransactionAudit])
  async transactionAudits(
    @graphql.Args() args: TransactionAuditFindManyArgs
  ): Promise<TransactionAudit[]> {
    return this.service.transactionAudits(args);
  }

  @graphql.Query(() => TransactionAudit, { nullable: true })
  async transactionAudit(
    @graphql.Args() args: TransactionAuditFindUniqueArgs
  ): Promise<TransactionAudit | null> {
    const result = await this.service.transactionAudit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TransactionAudit)
  async deleteTransactionAudit(
    @graphql.Args() args: DeleteTransactionAuditArgs
  ): Promise<TransactionAudit | null> {
    try {
      return await this.service.deleteTransactionAudit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
