/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { NftService } from "../nft.service";
import { NftCreateInput } from "./NftCreateInput";
import { Nft } from "./Nft";
import { NftFindManyArgs } from "./NftFindManyArgs";
import { NftWhereUniqueInput } from "./NftWhereUniqueInput";
import { NftUpdateInput } from "./NftUpdateInput";

export class NftControllerBase {
  constructor(protected readonly service: NftService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Nft })
  async createNft(@common.Body() data: NftCreateInput): Promise<Nft> {
    return await this.service.createNft({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Nft] })
  @ApiNestedQuery(NftFindManyArgs)
  async nfts(@common.Req() request: Request): Promise<Nft[]> {
    const args = plainToClass(NftFindManyArgs, request.query);
    return this.service.nfts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Nft })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async nft(@common.Param() params: NftWhereUniqueInput): Promise<Nft | null> {
    const result = await this.service.nft({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Nft })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateNft(
    @common.Param() params: NftWhereUniqueInput,
    @common.Body() data: NftUpdateInput
  ): Promise<Nft | null> {
    try {
      return await this.service.updateNft({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Nft })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteNft(
    @common.Param() params: NftWhereUniqueInput
  ): Promise<Nft | null> {
    try {
      return await this.service.deleteNft({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
