/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Grant } from "./Grant";
import { GrantCountArgs } from "./GrantCountArgs";
import { GrantFindManyArgs } from "./GrantFindManyArgs";
import { GrantFindUniqueArgs } from "./GrantFindUniqueArgs";
import { DeleteGrantArgs } from "./DeleteGrantArgs";
import { GrantService } from "../grant.service";
@graphql.Resolver(() => Grant)
export class GrantResolverBase {
  constructor(protected readonly service: GrantService) {}

  async _grantsMeta(
    @graphql.Args() args: GrantCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Grant])
  async grants(@graphql.Args() args: GrantFindManyArgs): Promise<Grant[]> {
    return this.service.grants(args);
  }

  @graphql.Query(() => Grant, { nullable: true })
  async grant(
    @graphql.Args() args: GrantFindUniqueArgs
  ): Promise<Grant | null> {
    const result = await this.service.grant(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Grant)
  async deleteGrant(
    @graphql.Args() args: DeleteGrantArgs
  ): Promise<Grant | null> {
    try {
      return await this.service.deleteGrant(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
