/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrantService } from "../grant.service";
import { GrantCreateInput } from "./GrantCreateInput";
import { Grant } from "./Grant";
import { GrantFindManyArgs } from "./GrantFindManyArgs";
import { GrantWhereUniqueInput } from "./GrantWhereUniqueInput";
import { GrantUpdateInput } from "./GrantUpdateInput";

export class GrantControllerBase {
  constructor(protected readonly service: GrantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Grant })
  async createGrant(@common.Body() data: GrantCreateInput): Promise<Grant> {
    return await this.service.createGrant({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Grant] })
  @ApiNestedQuery(GrantFindManyArgs)
  async grants(@common.Req() request: Request): Promise<Grant[]> {
    const args = plainToClass(GrantFindManyArgs, request.query);
    return this.service.grants({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Grant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async grant(
    @common.Param() params: GrantWhereUniqueInput
  ): Promise<Grant | null> {
    const result = await this.service.grant({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Grant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGrant(
    @common.Param() params: GrantWhereUniqueInput,
    @common.Body() data: GrantUpdateInput
  ): Promise<Grant | null> {
    try {
      return await this.service.updateGrant({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Grant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGrant(
    @common.Param() params: GrantWhereUniqueInput
  ): Promise<Grant | null> {
    try {
      return await this.service.deleteGrant({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
