/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Fork } from "./Fork";
import { ForkCountArgs } from "./ForkCountArgs";
import { ForkFindManyArgs } from "./ForkFindManyArgs";
import { ForkFindUniqueArgs } from "./ForkFindUniqueArgs";
import { DeleteForkArgs } from "./DeleteForkArgs";
import { ForkService } from "../fork.service";
@graphql.Resolver(() => Fork)
export class ForkResolverBase {
  constructor(protected readonly service: ForkService) {}

  async _forksMeta(
    @graphql.Args() args: ForkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Fork])
  async forks(@graphql.Args() args: ForkFindManyArgs): Promise<Fork[]> {
    return this.service.forks(args);
  }

  @graphql.Query(() => Fork, { nullable: true })
  async fork(@graphql.Args() args: ForkFindUniqueArgs): Promise<Fork | null> {
    const result = await this.service.fork(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fork)
  async deleteFork(@graphql.Args() args: DeleteForkArgs): Promise<Fork | null> {
    try {
      return await this.service.deleteFork(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
