/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Kyc } from "./Kyc";
import { KycCountArgs } from "./KycCountArgs";
import { KycFindManyArgs } from "./KycFindManyArgs";
import { KycFindUniqueArgs } from "./KycFindUniqueArgs";
import { DeleteKycArgs } from "./DeleteKycArgs";
import { KycService } from "../kyc.service";
@graphql.Resolver(() => Kyc)
export class KycResolverBase {
  constructor(protected readonly service: KycService) {}

  async _kycsMeta(
    @graphql.Args() args: KycCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Kyc])
  async kycs(@graphql.Args() args: KycFindManyArgs): Promise<Kyc[]> {
    return this.service.kycs(args);
  }

  @graphql.Query(() => Kyc, { nullable: true })
  async kyc(@graphql.Args() args: KycFindUniqueArgs): Promise<Kyc | null> {
    const result = await this.service.kyc(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Kyc)
  async deleteKyc(@graphql.Args() args: DeleteKycArgs): Promise<Kyc | null> {
    try {
      return await this.service.deleteKyc(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
