/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Miner as PrismaMiner } from "@prisma/client";

export class MinerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MinerCountArgs, "select">): Promise<number> {
    return this.prisma.miner.count(args);
  }

  async miners(args: Prisma.MinerFindManyArgs): Promise<PrismaMiner[]> {
    return this.prisma.miner.findMany(args);
  }
  async miner(args: Prisma.MinerFindUniqueArgs): Promise<PrismaMiner | null> {
    return this.prisma.miner.findUnique(args);
  }
  async createMiner(args: Prisma.MinerCreateArgs): Promise<PrismaMiner> {
    return this.prisma.miner.create(args);
  }
  async updateMiner(args: Prisma.MinerUpdateArgs): Promise<PrismaMiner> {
    return this.prisma.miner.update(args);
  }
  async deleteMiner(args: Prisma.MinerDeleteArgs): Promise<PrismaMiner> {
    return this.prisma.miner.delete(args);
  }
}
