/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Nonce } from "./Nonce";
import { NonceCountArgs } from "./NonceCountArgs";
import { NonceFindManyArgs } from "./NonceFindManyArgs";
import { NonceFindUniqueArgs } from "./NonceFindUniqueArgs";
import { DeleteNonceArgs } from "./DeleteNonceArgs";
import { NonceService } from "../nonce.service";
@graphql.Resolver(() => Nonce)
export class NonceResolverBase {
  constructor(protected readonly service: NonceService) {}

  async _noncesMeta(
    @graphql.Args() args: NonceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Nonce])
  async nonces(@graphql.Args() args: NonceFindManyArgs): Promise<Nonce[]> {
    return this.service.nonces(args);
  }

  @graphql.Query(() => Nonce, { nullable: true })
  async nonce(
    @graphql.Args() args: NonceFindUniqueArgs
  ): Promise<Nonce | null> {
    const result = await this.service.nonce(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Nonce)
  async deleteNonce(
    @graphql.Args() args: DeleteNonceArgs
  ): Promise<Nonce | null> {
    try {
      return await this.service.deleteNonce(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
