/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ZeroKnowledgeProof as PrismaZeroKnowledgeProof,
} from "@prisma/client";

export class ZeroKnowledgeProofServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ZeroKnowledgeProofCountArgs, "select">
  ): Promise<number> {
    return this.prisma.zeroKnowledgeProof.count(args);
  }

  async zeroKnowledgeProofs(
    args: Prisma.ZeroKnowledgeProofFindManyArgs
  ): Promise<PrismaZeroKnowledgeProof[]> {
    return this.prisma.zeroKnowledgeProof.findMany(args);
  }
  async zeroKnowledgeProof(
    args: Prisma.ZeroKnowledgeProofFindUniqueArgs
  ): Promise<PrismaZeroKnowledgeProof | null> {
    return this.prisma.zeroKnowledgeProof.findUnique(args);
  }
  async createZeroKnowledgeProof(
    args: Prisma.ZeroKnowledgeProofCreateArgs
  ): Promise<PrismaZeroKnowledgeProof> {
    return this.prisma.zeroKnowledgeProof.create(args);
  }
  async updateZeroKnowledgeProof(
    args: Prisma.ZeroKnowledgeProofUpdateArgs
  ): Promise<PrismaZeroKnowledgeProof> {
    return this.prisma.zeroKnowledgeProof.update(args);
  }
  async deleteZeroKnowledgeProof(
    args: Prisma.ZeroKnowledgeProofDeleteArgs
  ): Promise<PrismaZeroKnowledgeProof> {
    return this.prisma.zeroKnowledgeProof.delete(args);
  }
}
