/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Chain } from "./Chain";
import { ChainCountArgs } from "./ChainCountArgs";
import { ChainFindManyArgs } from "./ChainFindManyArgs";
import { ChainFindUniqueArgs } from "./ChainFindUniqueArgs";
import { DeleteChainArgs } from "./DeleteChainArgs";
import { ChainService } from "../chain.service";
@graphql.Resolver(() => Chain)
export class ChainResolverBase {
  constructor(protected readonly service: ChainService) {}

  async _chainsMeta(
    @graphql.Args() args: ChainCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Chain])
  async chains(@graphql.Args() args: ChainFindManyArgs): Promise<Chain[]> {
    return this.service.chains(args);
  }

  @graphql.Query(() => Chain, { nullable: true })
  async chain(
    @graphql.Args() args: ChainFindUniqueArgs
  ): Promise<Chain | null> {
    const result = await this.service.chain(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Chain)
  async deleteChain(
    @graphql.Args() args: DeleteChainArgs
  ): Promise<Chain | null> {
    try {
      return await this.service.deleteChain(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
